#!/bin/bash -x
VERSION=3.0.1

# Salmon Vault javascript
OUTPUT_ROOT=../../output
OUTPUT_DIR=$OUTPUT_ROOT/javafx
SALMON_VAULT_JAR=./build/libs/salmon-vault-$VERSION.jar
SALMON_LIBS_DIR=./libs/salmon
JAVAFX_LIBS_DIR=./libs/javafx
DEPS_LIBS_DIR=./libs/libs
SALMON_NATIVE_LIBS_DIR=./build/libs/natives/lib
SALMON_SCRIPTS_DIR=./scripts

PACKAGES_DIR=app_package
SALMON_VAULT=salmon-vault-javafx
SALMON_VAULT_PACKAGE_NAME=$SALMON_VAULT.$VERSION

mkdir -p $PACKAGES_DIR
rm -rf $PACKAGES_DIR/*

mkdir -p $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME/*

cp -r $SALMON_LIBS_DIR $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME
cp -r $SALMON_VAULT_JAR $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME/salmon
cp -r $JAVAFX_LIBS_DIR $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME
cp -r $DEPS_LIBS_DIR $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME
cp -r $SALMON_NATIVE_LIBS_DIR/*.dll $SALMON_NATIVE_LIBS_DIR/*.so $SALMON_NATIVE_LIBS_DIR/*.dylib $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME/salmon
cp -r $SALMON_SCRIPTS_DIR/* $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME
cp README.txt $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME

cd $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME
zip -r ../$SALMON_VAULT_PACKAGE_NAME.zip *
cd ../../
mkdir -p $OUTPUT_DIR
cp -f $PACKAGES_DIR/$SALMON_VAULT_PACKAGE_NAME.zip $OUTPUT_DIR

