#!/bin/bash
VERSION=3.0.1

# Salmon Vault javascript
OUTPUT_ROOT=../../output
JS_OUTPUT_DIR=$OUTPUT_ROOT/javascript
JS_VAULT_SRC=../src
JS_COMMON_RES=../../common/common-res

PACKAGES_DIR=app_package
SALMON_VAULT=salmon-vault-js
JS_SALMON_VAULT_PACKAGE_NAME=$SALMON_VAULT.$VERSION

mkdir -p $PACKAGES_DIR
rm -rf $PACKAGES_DIR/*

mkdir -p $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME/*
cp -r $JS_VAULT_SRC/* $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cp -r $JS_COMMON_RES $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME/assets/images/
cp README.txt $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cd $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
zip -r ../$JS_SALMON_VAULT_PACKAGE_NAME.zip *
cd ../../
mkdir -p $JS_OUTPUT_DIR
cp -f $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME.zip $JS_OUTPUT_DIR
