#!/bin/bash

# Salmon Vault javascript
JS_LIB_ROOT=./lib
OUTPUT_ROOT=../../output
JS_OUTPUT_DIR=$OUTPUT_ROOT/javascript
CSS=../css
JS_VAULT_SRC=../src/vault
JS_COMMON_SRC=../../js-common/src/common
JS_COMMON_RES=../../common/common-res
FAVICON=../../common/common-res/icons/logo_48x48.ico

VERSION=2.1.0
PACKAGES_DIR=app_package
SALMON_VAULT=salmon-vault-js
JS_SALMON_VAULT_PACKAGE_NAME=$SALMON_VAULT.$VERSION

mkdir -p $PACKAGES_DIR
rm -rf $PACKAGES_DIR/*

mkdir -p $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME/*
cp -r $JS_LIB_ROOT $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cp -r $JS_VAULT_SRC $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cp -r $JS_COMMON_SRC $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cp -r $JS_COMMON_RES $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cp -r $CSS $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cp -r $FAVICON $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME/favicon.ico
cp -r *.html *.js $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cp README.txt $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
cd $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME
zip -r ../$JS_SALMON_VAULT_PACKAGE_NAME.zip *
cd ../../
mkdir -p $JS_OUTPUT_DIR
cp -f $PACKAGES_DIR/$JS_SALMON_VAULT_PACKAGE_NAME.zip $JS_OUTPUT_DIR
