# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# Build, Package, and Release
# This workflow should only run in the main branch

# Note: if you have cache misses then make sure this workflow runs in the main branch first for the same cache keys.
name: CD.BuildPackageRelease

on:
  push:
    tags:
      - "v*.*.*"


jobs: 

  javafx_build_matrix:
    strategy:
      matrix:
        java_version: [11]
        os: [windows-latest,ubuntu-latest,ubuntu-24.04-arm,macos-15-intel,macos-latest]
    name: build.javafx.${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    
    # Git
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    
    - if: runner.os == 'Windows'
      name: Setup on Windows
      shell: cmd
      run: setup.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Setup on Linux/MacOS
      shell: bash
      run: ./setup.sh
    
    # Toolchains and Build envs
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    
    # Caches
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    # Gradle Build JavaFx App
    - if: runner.os == 'Windows'
      name: Build JavaFx App on Windows
      shell: cmd
      run: cd .\javafx\project && gradlew.bat build -x test -i && package.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Build JavaFx App on Linux/MacOS
      shell: bash
      run: cd ./javafx/project && ./gradlew build -x test -i && ./package.sh 
      
    # Rename Package
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Rename Java Windows x64 Package
      shell: cmd
      run: cd .\output\javafx && ren salmon-vault-javafx.zip salmon-vault-javafx-win-x86_64.${{ github.ref_name }}.zip
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Rename Java Linux x64 Package
      shell: bash
      run: cd ./output/javafx && mv salmon-vault-javafx.zip salmon-vault-javafx-linux-x86_64.${{ github.ref_name }}.zip
    - if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
      name: Rename Java Linux aarch64 Package
      shell: bash
      run: cd ./output/javafx && mv salmon-vault-javafx.zip salmon-vault-javafx-linux-aarch64.${{ github.ref_name }}.zip
    - if: ${{ matrix.os == 'macos-15-intel' }}
      name: Rename Java MacOS aarch64 Package
      shell: bash
      run: cd ./output/javafx && mv salmon-vault-javafx.zip salmon-vault-javafx-macos-x86_64.${{ github.ref_name }}.zip
    - if: ${{ matrix.os == 'macos-latest' }}
      name: Rename Java MacOS aarch64 Package
      shell: bash
      run: cd ./output/javafx && mv salmon-vault-javafx.zip salmon-vault-javafx-macos-aarch64.${{ github.ref_name }}.zip
      
    # Upload JavaFx App
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Upload Java Windows x64 Packages
      uses: actions/upload-artifact@v4
      with:
        name: salmon-vault-javafx-win-x86_64
        path: output/javafx
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Upload Java Linux x64 Packages
      uses: actions/upload-artifact@v4
      with:
        name: salmon-vault-javafx-linux-x86_64
        path: output/javafx
    - if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
      name: Upload Java Linux aarch64 Packages
      uses: actions/upload-artifact@v4
      with:
        name: salmon-vault-javafx-linux-aarch64
        path: output/javafx
    - if: ${{ matrix.os == 'macos-15-intel' }}
      name: Upload JavaFx MacOS x64 Packages
      uses: actions/upload-artifact@v4
      with:
        name: salmon-vault-javafx-macos-x86_64
        path: output/javafx
    - if: ${{ matrix.os == 'macos-latest' }}
      name: Upload JavaFx MacOS aarch64 Packages
      uses: actions/upload-artifact@v4
      with:
        name: salmon-vault-javafx-macos-aarch64
        path: output/javafx
        
    # Release
    - if: github.ref_type == 'tag'
      name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: output/javafx/*

  android_build_matrix:
    strategy:
      matrix:
        java_version: [11]
        os: [windows-latest]
    name: build.android.java${{ matrix.java_version }}. ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    
    # Git
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - if: runner.os == 'Windows'
      name: Setup on Windows
      shell: cmd
      run: setup.bat
    
    # Toolchains and Build envs
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    
    # Caches
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    # Gradle Build Android App
    - if: runner.os == 'Windows'
      name: Build Android App
      shell: cmd
      run: cd .\android\project && gradlew.bat assemble -x test -i
    
    # Rename Android App
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Rename Android App
      shell: cmd
      run: cd android\project\app\build\outputs\apk\release && ren app-release-unsigned.apk salmon-vault-android-unsinged.${{ github.ref_name }}.apk
      
    # Upload Android App
    - if: runner.os == 'Windows'
      name: Upload Android App
      uses: actions/upload-artifact@v4
      with:
        name: salmon-vault-android
        path: android/project/app/build/outputs/apk/release/*.apk
        
    # Release
    - if: github.ref_type == 'tag'
      name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: android/project/app/build/outputs/apk/release/salmon-vault-android-unsinged.${{ github.ref_name }}.apk
        
        
  # WPF
  wpf_build_matrix:
    strategy:
      matrix:
        dotnet_version: [9.0.x]
        os: [windows-latest]
    name: build.dotnet${{ matrix.dotnet_version }}.${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    
    # Git
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - if: runner.os == 'Windows'
      name: Setup on Windows
      shell: cmd
      run: setup.bat
    
    # Toolchains and Build envs
    - if: runner.os == 'Windows'
      name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Setup Nuget
      uses: nuget/setup-nuget@v2
      
    # Caches
    - name: Cache Nuget packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.vcxproj*', '**/*.csproj', '**/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
            
    # MSBuild Build
    - if: runner.os == 'Windows'
      name: Restore NuGet Packages
      shell: cmd
      run: cd .\wpf\project && msbuild -t:restore /property:Configuration=Release
    - if: runner.os == 'Windows'
      name: Build WPF App on Windows
      shell: cmd
      run: cd .\wpf\project && msbuild /property:Configuration=Release
    
    # Publish WPF App
    - if: runner.os == 'Windows'
      name: Publish WPF App
      shell: cmd
      run: cd .\wpf\project && msbuild /t:publish /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml /p:Configuration=Release
    
    # Package WPF App
    - if: runner.os == 'Windows'
      name: Package WPF App
      shell: cmd
      run: cd .\wpf\project\Salmon.Vault.WPF && package.bat
    
    # Rename WPF App
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Rename WPF App
      shell: cmd
      run: cd .\output\wpf && ren salmon-vault-wpf.zip salmon-vault-wpf-win-x86_64.${{ github.ref_name }}.zip
      
    # Upload WPF App
    - if: runner.os == 'Windows'
      name: Upload WPF App
      uses: actions/upload-artifact@v4
      with:
        name: salmon-vault-wpf
        path: output/wpf
     
    # Release
    - if: github.ref_type == 'tag'
      name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: ./output/wpf/salmon-vault-wpf-win-x86_64.${{ github.ref_name }}.zip
        
  # .NET Android
  dotnet_android_build_matrix:
    strategy:
      matrix:
        dotnet_version: [9.0.x]
        os: [windows-latest]
    name: build.android.dotnet.${{ matrix.dotnet_version }}.${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    
    # Git
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - if: runner.os == 'Windows'
      name: Setup on Windows
      shell: cmd
      run: setup.bat
    
    # Toolchains and Build envs
    - if: runner.os == 'Windows'
      name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - if: runner.os == 'Windows'
      name: Setup .NET
      uses: actions/setup-dotnet@v4
    - if: runner.os == 'Windows'
      name: Install Android Workload
      run: dotnet workload install android
    - name: Setup Nuget
      uses: nuget/setup-nuget@v2
      
    # Caches
    - name: Cache Nuget packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.vcxproj*', '**/*.csproj', '**/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    # MSBuild Build
    - if: runner.os == 'Windows'
      name: Restore .NET dependencies
      shell: cmd
      run: cd .\dotnet-android\project && msbuild -t:restore /property:Configuration=Release
    - if: runner.os == 'Windows'
      name: Build .NET Android App on Windows
      shell: cmd
      run: cd .\dotnet-android\project && msbuild /property:Configuration=Release

    # Rename .NET Android App
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Rename .NET Android App
      shell: cmd
      run: cd output\dotnet-android\project\Salmon.Vault.Net.Android\bin\Release && ren com.mku.salmon.vault.net.android.apk salmon-vault-dotnet-android-unsigned.${{ github.ref_name }}.apk
      
    # Upload .NET Android App
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Upload .NET Android App
      uses: actions/upload-artifact@v4
      with:
        name: salmon-vault-dotnet-android
        path: output/dotnet-android/project/Salmon.Vault.Net.Android/bin/Release/*.apk
    
    # Release
    - if: github.ref_type == 'tag'
      name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: output/dotnet-android/project/Salmon.Vault.Net.Android/bin/Release/salmon-vault-dotnet-android-unsigned.${{ github.ref_name }}.apk
